### ISSUE TITLE
Add notebook here in repo also

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/Natural-Language-Processing#1]
You can directly commit notebooks here using colab

**Comment by GlazeDonuts** [comment]
Yes but we don't want to "commit" notebooks so that the repo remains as light as possible

**Comment by GlazeDonuts** [comment]
Please close the issue if resolved :)

**Comment by take2rohit** [comment]
I thinks it's a good option to add your files here also. But its your call totally. 
You can close this issue yourself! U r the admin of this repo
